"""add reflection field to journal entry

Revision ID: 74920cfa29c9
Revises: 52e8b9ba5d36
Create Date: 2025-07-13 16:14:50.710313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74920cfa29c9'
down_revision: Union[str, Sequence[str], None] = '52e8b9ba5d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journalentry', sa.Column('reflection', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journalentry', 'reflection')
    # ### end Alembic commands ###
